compile:
	g++ *.cc -o proj2
run:
	./proj2 test1.txt
run2:
	./proj2 test2.txt
run3:
	./proj2 test3.txt
run4:
	./proj2 test4.txt
run5:
	./proj2 test5.txt
run6:
	./proj2 insertOnlyTest.txt
run7:
	./proj2 insertDeleteTest.txt
clean:
	rm -Rf proj2
